// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG5lTAC29Exd_tGbHODe028jaRE1Bg8wU',
    appId: '1:365278455758:web:5a917dda6d1d0105c92d9f',
    messagingSenderId: '365278455758',
    projectId: 'smartmedicineremider',
    authDomain: 'smartmedicineremider.firebaseapp.com',
    storageBucket: 'smartmedicineremider.firebasestorage.app',
    measurementId: 'G-8YRCE78R19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtwYvRG6iHjAUvVNyFlNosIFZUjqrFC34',
    appId: '1:365278455758:android:84bd8abadf7042a2c92d9f',
    messagingSenderId: '365278455758',
    projectId: 'smartmedicineremider',
    storageBucket: 'smartmedicineremider.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGtUZ5o8Ks0sQg_QubJmjv-Fa6JzSaw2w',
    appId: '1:365278455758:ios:606df2d66bf06b43c92d9f',
    messagingSenderId: '365278455758',
    projectId: 'smartmedicineremider',
    storageBucket: 'smartmedicineremider.firebasestorage.app',
    iosBundleId: 'com.example.smartMedicineReminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGtUZ5o8Ks0sQg_QubJmjv-Fa6JzSaw2w',
    appId: '1:365278455758:ios:606df2d66bf06b43c92d9f',
    messagingSenderId: '365278455758',
    projectId: 'smartmedicineremider',
    storageBucket: 'smartmedicineremider.firebasestorage.app',
    iosBundleId: 'com.example.smartMedicineReminder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG5lTAC29Exd_tGbHODe028jaRE1Bg8wU',
    appId: '1:365278455758:web:d493a9e1e171428ec92d9f',
    messagingSenderId: '365278455758',
    projectId: 'smartmedicineremider',
    authDomain: 'smartmedicineremider.firebaseapp.com',
    storageBucket: 'smartmedicineremider.firebasestorage.app',
    measurementId: 'G-RHBQXFLX6S',
  );

}